CLS
SCREEN _NEWIMAGE(600, 600, 256)
DECLARE SUB FPSLimit()
DECLARE SUB CheckKey()
RANDOMIZE TIMER / 3
DIM SHARED LastFrame AS SINGLE
TIMER ON
DIM SHARED MAXFPS AS INTEGER
MAXFPS = 60
DIM SHARED GAMESTATUS AS INTEGER
GAMESTATUS = 1

WHILE GAMESTATUS = 1
    LastFrame = TIMER
    LINE (INT(RND * 600), INT(RND * 600))-(INT(RND * 600), INT(RND * 600)), INT(RND * 10)
    CheckKey
    FPSLimit
WEND

SUB FPSLimit ()
    DO
        CheckKey
    LOOP UNTIL TIMER - LastFrame > 1 / MAXFPS
END SUB

SUB CheckKey ()
    IF INKEY$ = "Q" OR INKEY$ = "q" THEN
        GAMESTATUS = 0
    ELSEIF INKEY$ = "C" OR INKEY$ = "c" THEN
        CLS
    END IF
END SUB
